
default: &default
  adapter: postgresql
  encoding: unicode
  database: notes_project
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notes_project_development

test:
  <<: *default
  database: notes_project_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>